### ISSUE TITLE
Unexpected torchvision behaviour

### ISSUE THREAD

**Issue by danyanyam** [abdalazizrashid/idao-21-baseline#8]
Hello! 

I am trying to submit my solution to track-2, which depends on torchvision pretrained models. When i am compiling my model, i have to load the model itself and then pass weights, which i have previously trained. In my code it looks like this:

```python
def compile_model(self, kind):
        model = torchvision.models.mobilenet_v3_small(pretrained=False)

        if kind == 'classifier':
            model.classifier[-1] = torch.nn.Linear(1024, 2)
            weights = torch.load(self.CLASSIFICATION_PATH,
             map_location=torch.device(self.device))
        else:
            model.classifier[-1] = torch.nn.Linear(1024, 6)
            weights = torch.load(self.REGRESSION_PATH,
             map_location=torch.device(self.device))
        
        model.load_state_dict(weights)
        return model
```

Yandex contest throws an error, saying that there is no such model in torchvision. I installed torchvision version from yours `requirements.txt` and in my local machine everything runs fine. Could you please help me, because i think there might be a problem with environment installation in Yandex Contest. Thanks!

Error:
File "track2_class.py", line 20, in compile_model
    model = torchvision.models.mobilenet_v3_small(pretrained=False)
AttributeError: module 'torchvision.models' has no attribute 'mobilenet_v3_small'

**Comment by abdalazizrashid** [comment]
Check the version of your local `torchvision` I'm sure it's not the same as in the requirements just run `python -c "import torchvision as tv; print(tv.__version__)"` 
These are the available models in  the current torchvision version:
```
['AlexNet', 'DenseNet', 'GoogLeNet', 'GoogLeNetOutputs', 'Inception3', 'InceptionOutputs', 'MNASNet', 'MobileNetV2', 'ResNet', 'ShuffleNetV2', 'SqueezeNet', 'VGG', '_GoogLeNetOutputs', '_InceptionOutputs', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_utils', 'alexnet', 'densenet', 'densenet121', 'densenet161', 'densenet169', 'densenet201', 'detection', 'googlenet', 'inception', 'inception_v3', 'mnasnet', 'mnasnet0_5', 'mnasnet0_75', 'mnasnet1_0', 'mnasnet1_3', 'mobilenet', 'mobilenet_v2', 'quantization', 'resnet', 'resnet101', 'resnet152', 'resnet18', 'resnet34', 'resnet50', 'resnext101_32x8d', 'resnext50_32x4d', 'segmentation', 'shufflenet_v2_x0_5', 'shufflenet_v2_x1_0', 'shufflenet_v2_x1_5', 'shufflenet_v2_x2_0', 'shufflenetv2', 'squeezenet', 'squeezenet1_0', 'squeezenet1_1', 'utils', 'vgg', 'vgg11', 'vgg11_bn', 'vgg13', 'vgg13_bn', 'vgg16', 'vgg16_bn', 'vgg19', 'vgg19_bn', 'video', 'wide_resnet101_2', 'wide_resnet50_2']
```

**Comment by danyanyam** [comment]
My version of torchvision:

<img width="756" alt="Снимок экрана 2021-03-15 в 17 44 10" src="https://user-images.githubusercontent.com/48715538/111171516-0dfa9480-85b6-11eb-9f15-c9d3247283a0.png">

Screenshot from `requirements.txt`:


<img width="693" alt="Снимок экрана 2021-03-15 в 17 45 40" src="https://user-images.githubusercontent.com/48715538/111171841-57e37a80-85b6-11eb-8a9c-6d3dcf582e8c.png">

**Comment by danyanyam** [comment]
I guess all i left to do is to choose different model, because it seems like other models are available.

**Comment by abdalazizrashid** [comment]
Ah, you mean the requirements of this baseline, in Yandex Contest instance: torchvision==0.8.2
The requirements of this baseline are different than the one in the actual Yandex Contest instance.

**Comment by danyanyam** [comment]
Okay, thank you, i close the issue
